# Travis CI (https://travis-ci.org/) is a continuous integration service for
# open source projects. This file uses the default travis behaviour for go
# projects: run unit tests on the code (go test -v ./...).

language: go
go: 1.8

# Don't use the default clone depth value (50), it is too much.
git:
    depth: 3

# Use a container based virtual environment for the build.
# This is the default for repos enabled since 2015 and much
# faster than the sudo-enabled build.
sudo: false

notifications:
    email: false

script:
    - go tool vet -all .
    # Run unit test and generate coverage report
    - bash test-and-coverage.bash

after_success:
    # Send coverage reports to Codecov (https://codecov.io, a web
    # service to explore coverage reports)
    - bash <(curl -s https://codecov.io/bash)

